Results of doctest builder run on 2018-11-21 00:57:22
=====================================================

Document: index
---------------
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    is_prime(37)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        is_prime(37)
    NameError: name 'is_prime' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    is_prime(100)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        is_prime(100)
    NameError: name 'is_prime' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    is_prime(89)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        is_prime(89)
    NameError: name 'is_prime' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    list(prime_factorization_gen(12))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        list(prime_factorization_gen(12))
    NameError: name 'prime_factorization_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    list(prime_factorization_gen(16))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        list(prime_factorization_gen(16))
    NameError: name 'prime_factorization_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    list(prime_factors_gen(12))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        list(prime_factors_gen(12))
    NameError: name 'prime_factors_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    list(prime_factors_gen(16))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        list(prime_factors_gen(16))
    NameError: name 'prime_factors_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    list(prime_gen(50))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        list(prime_gen(50))
    NameError: name 'prime_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\amazon_prime.py", line ?, in default
Failed example:
    list(prime_gen(10))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        list(prime_gen(10))
    NameError: name 'prime_gen' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(1111)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        digits_list(1111)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(982)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        digits_list(982)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(101)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        digits_list(101)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(123)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[3]>", line 1, in <module>
        digits_list(123)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    int_from_digits([3, 2, 1])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        int_from_digits([3, 2, 1])
    NameError: name 'int_from_digits' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    int_from_digits([1, 1, 1, 1, 2, 3])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        int_from_digits([1, 1, 1, 1, 2, 3])
    NameError: name 'int_from_digits' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    int_from_digits([1, 2, 3])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        int_from_digits([1, 2, 3])
    NameError: name 'int_from_digits' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    iter_product([1, 2, 3, 4])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        iter_product([1, 2, 3, 4])
    NameError: name 'iter_product' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    iter_product(tuple([1, 2, 3, 4]))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        iter_product(tuple([1, 2, 3, 4]))
    NameError: name 'iter_product' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    iter_product([-1, -2, -3, 4])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        iter_product([-1, -2, -3, 4])
    NameError: name 'iter_product' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    rotate([1, 2, 3, 4], left_rotate=True)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        rotate([1, 2, 3, 4], left_rotate=True)
    NameError: name 'rotate' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    rotate([1, 2, 3, 4], left_rotate=False)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        rotate([1, 2, 3, 4], left_rotate=False)
    NameError: name 'rotate' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    rotate([1, 2, 3, 4], rn=4, left_rotate=False)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        rotate([1, 2, 3, 4], rn=4, left_rotate=False)
    NameError: name 'rotate' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    for rot in rotations_gen((1, 2, 3, 4)):
        print(rot)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        for rot in rotations_gen((1, 2, 3, 4)):
    NameError: name 'rotations_gen' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    v = Vuple((3, 4, 5))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        v = Vuple((3, 4, 5))
    NameError: name 'Vuple' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(1)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        fib_r(1)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(2)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        fib_r(2)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(6)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        fib_r(6)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    v = Vuple((3, 4, 5))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        v = Vuple((3, 4, 5))
    NameError: name 'Vuple' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(1)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        fib_r(1)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(2)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        fib_r(2)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(6)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        fib_r(6)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    v = Vuple((3, 4, 5))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        v = Vuple((3, 4, 5))
    NameError: name 'Vuple' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(1111)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        digits_list(1111)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(982)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        digits_list(982)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(101)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        digits_list(101)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    digits_list(123)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[3]>", line 1, in <module>
        digits_list(123)
    NameError: name 'digits_list' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(1)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        fib_r(1)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(2)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        fib_r(2)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    fib_r(6)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        fib_r(6)
    NameError: name 'fib_r' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    int_from_digits([3, 2, 1])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        int_from_digits([3, 2, 1])
    NameError: name 'int_from_digits' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    int_from_digits([1, 1, 1, 1, 2, 3])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        int_from_digits([1, 1, 1, 1, 2, 3])
    NameError: name 'int_from_digits' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    int_from_digits([1, 2, 3])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        int_from_digits([1, 2, 3])
    NameError: name 'int_from_digits' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    is_palindrome("racecar")
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        is_palindrome("racecar")
    NameError: name 'is_palindrome' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    is_palindrome("greg")
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        is_palindrome("greg")
    NameError: name 'is_palindrome' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    is_prime(37)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        is_prime(37)
    NameError: name 'is_prime' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    is_prime(100)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        is_prime(100)
    NameError: name 'is_prime' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    is_prime(89)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        is_prime(89)
    NameError: name 'is_prime' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    iter_product([1, 2, 3, 4])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        iter_product([1, 2, 3, 4])
    NameError: name 'iter_product' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    iter_product(tuple([1, 2, 3, 4]))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        iter_product(tuple([1, 2, 3, 4]))
    NameError: name 'iter_product' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    iter_product([-1, -2, -3, 4])
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        iter_product([-1, -2, -3, 4])
    NameError: name 'iter_product' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    list(prime_factorization_gen(12))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        list(prime_factorization_gen(12))
    NameError: name 'prime_factorization_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    list(prime_factorization_gen(16))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        list(prime_factorization_gen(16))
    NameError: name 'prime_factorization_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    list(prime_factors_gen(12))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        list(prime_factors_gen(12))
    NameError: name 'prime_factors_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    list(prime_factors_gen(16))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        list(prime_factors_gen(16))
    NameError: name 'prime_factors_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    list(prime_gen(50))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        list(prime_gen(50))
    NameError: name 'prime_gen' is not defined
**********************************************************************
File "..\..\..\scoop\apps\python\3.7.1\lib\site-packages\pupy\__init__.py", line ?, in default
Failed example:
    list(prime_gen(10))
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        list(prime_gen(10))
    NameError: name 'prime_gen' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    rotate([1, 2, 3, 4], left_rotate=True)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        rotate([1, 2, 3, 4], left_rotate=True)
    NameError: name 'rotate' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    rotate([1, 2, 3, 4], left_rotate=False)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        rotate([1, 2, 3, 4], left_rotate=False)
    NameError: name 'rotate' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    rotate([1, 2, 3, 4], rn=4, left_rotate=False)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        rotate([1, 2, 3, 4], rn=4, left_rotate=False)
    NameError: name 'rotate' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    for rot in rotations_gen((1, 2, 3, 4)):
        print(rot)
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        for rot in rotations_gen((1, 2, 3, 4)):
    NameError: name 'rotations_gen' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    string_score('me')
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        string_score('me')
    NameError: name 'string_score' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    string_score('poooood')
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        string_score('poooood')
    NameError: name 'string_score' is not defined
**********************************************************************
File "index.rst", line ?, in default
Failed example:
    string_score('gregory')
Exception raised:
    Traceback (most recent call last):
      File "c:\users\jesse\scoop\apps\python\3.7.1\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        string_score('gregory')
    NameError: name 'string_score' is not defined
**********************************************************************
1 items had failures:
  63 of  63 in default
63 tests in 1 items.
0 passed and 63 failed.
***Test Failed*** 63 failures.

Doctest summary
===============
   63 tests
   63 failures in tests
    0 failures in setup code
    0 failures in cleanup code
